export const jobRolesByCategory = {
  "Engineering / Development": [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile App Developer",
    "Software Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Site Reliability Engineer",
    "Embedded Systems Engineer",
    "Firmware Developer",
    "Game Developer",
    "Security Engineer",
    "Blockchain Developer",
    "AR/VR Developer",
    "QA Engineer",
    "Test Automation Engineer"
  ],
  "Data & AI": [
    "Data Scientist",
    "Data Analyst",
    "Business Intelligence Analyst",
    "Data Engineer",
    "Big Data Engineer",
    "Data Architect",
    "Machine Learning Engineer",
    "AI Engineer",
    "AI Researcher",
    "NLP Engineer",
    "Computer Vision Engineer",
    "Statistician"
  ],
  "Product & Design": [
    "Product Manager",
    "Technical Product Manager",
    "Product Owner",
    "UX Designer",
    "UI Designer",
    "UX Researcher",
    "Design Lead",
    "Graphic Designer",
    "Motion Designer",
    "Interaction Designer"
  ],
  "Marketing & Growth": [
    "Marketing Manager",
    "Digital Marketing Specialist",
    "Growth Hacker",
    "SEO Specialist",
    "Content Writer",
    "Content Strategist",
    "Brand Manager",
    "Social Media Manager",
    "Email Marketing Specialist",
    "Product Marketing Manager",
    "Performance Marketer",
    "PR Manager"
  ],
  "Sales & Customer": [
    "Sales Executive",
    "Sales Manager",
    "Account Executive",
    "Account Manager",
    "Business Development Executive",
    "Lead Generation Specialist",
    "Customer Success Manager",
    "Customer Support Specialist",
    "Inside Sales Representative",
    "Field Sales Representative"
  ],
  "HR & People": [
    "HR Manager",
    "Recruiter",
    "Technical Recruiter",
    "Talent Acquisition Specialist",
    "HR Business Partner",
    "HR Generalist",
    "HR Coordinator",
    "Employee Relations Specialist",
    "Learning & Development Manager"
  ],
  "Finance & Legal": [
    "Financial Analyst",
    "Accountant",
    "Auditor",
    "Controller",
    "Chief Financial Officer (CFO)",
    "Tax Consultant",
    "Legal Counsel",
    "Corporate Lawyer",
    "Compliance Officer"
  ],
  "Operations & Admin": [
    "Operations Manager",
    "Supply Chain Analyst",
    "Procurement Manager",
    "Inventory Analyst",
    "Logistics Coordinator",
    "Office Manager",
    "Administrative Assistant",
    "Executive Assistant"
  ],
  "Leadership & Strategy": [
    "Chief Executive Officer (CEO)",
    "Chief Technology Officer (CTO)",
    "Chief Operating Officer (COO)",
    "Chief Marketing Officer (CMO)",
    "Chief Product Officer (CPO)",
    "Chief Design Officer (CDO)",
    "VP of Engineering",
    "VP of Product",
    "VP of Sales",
    "Strategy Manager"
  ],
  "Others / Miscellaneous": [
    "Technical Writer",
    "IT Support Specialist",
    "System Administrator",
    "Network Engineer",
    "Ethical Hacker",
    "Penetration Tester",
    "Scrum Master",
    "Agile Coach",
    "Project Manager",
    "Program Manager",
    "Facilities Manager",
    "Training Coordinator"
  ]
};
